<?php
/**
 * @file
 * Code for the DGU Library feature.
 */

include_once 'dgu_library.features.inc';

/**
 * Implements hook_menu_breadcrumb_alter().
 */
function dgu_library_menu_breadcrumb_alter(&$active_trail, $item) {
  if (isset($item['map'][1]->type) && $item['map'][1]->type == 'resource') {
    $active_trail[2] = $active_trail[1];
    $active_trail[1] = array('title' => 'Library', 'href' => 'library', 'localized_options' => array());
  }
}