<?php

use ckan\ckan;
include_once "sites/all/libraries/composer/autoload.php";

function ckan_client_menu(){
    $items = array();
    $items['ckan_client'] = array(
        'title' => 'ckan_client',
        'page callback' => 'ckan_client_page',
        'access callback' => TRUE,
    );
    return $items;
}


function ckan_client_page(){
    $client = \ckan\ckan\CkanClient::factory(
        array(
            'baseUrl' => 'http://data.gov.uk/api/2/'
        )
    );
    $model = $client->GetDatasets();
    $datasets = $model->toArray();
    foreach($datasets as $uuid){
        $model = $client->GetDataset(array("id"=>$uuid));
        print_r($model->toArray());
    }

}


