<?php
/**
 * @file
 * Code for the DGU Home page feature.
 */

include_once 'dgu_home_page.features.inc';

/**
 * Implements hook_block_info().
 */
function dgu_home_page_block_info() {
  $blocks = array();
  $blocks['dgu_home_page_data_search'] = array(
    'info' => t('Home page data search'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function dgu_home_page_block_view($delta='') {
  $block = array();

  switch($delta) {
    case 'dgu_home_page_data_search' :
      $block['content'] = dgu_home_page_data_search_form();
      break;
  }
  return $block;
}

/**
 * Home page data search block content constructor.
 */
function dgu_home_page_data_search_form() {

  try {
    require_once 'sites/all/vendor/autoload.php';
    $client = Silex\ckan\CkanClient::factory(array(
        'baseUrl' => variable_get('ckan_url', ''),
        'apiKey' => variable_get('ckan_apikey', ''),
        ));

    // Get total number of datasets.
    $count = $client->GetDatasetCount();
  }
  catch (Exception $e) {
    watchdog('ckan_dataset_count', 'Error in getting total number of datasets');
    $count = FALSE;
  }
  return theme('home_page_data_search_box', array('count' => $count));
}

 /*
 * Implemnets hook_theme().
 */
function dgu_home_page_theme($existing, $type, $theme, $path) {
  return array(
    'home_page_data_search_box' => array(
      'arguments' => array(
        'count' => NULL,
      ),
      'template' => 'dgu_home_page_search',
    ),
  );
}

/*
* Implemnets hook_form_FORM_ID_alter().
*/
function dgu_home_page_form_apachesolr_panels_search_form_alter(&$form, $form_state, $form_id) {
  $form['apachesolr_panels_search_form']['#attributes']['placeholder'] = 'search other content';
}
