<?php
/**
 * @file
 * Code for the dgu search feature.
 */

include_once 'dgu_search.features.inc';

/**
* Implements hook_apachesolr_prepare_query().
*/
function dgu_search_apachesolr_query_prepare($query, $caller) {
  $query->removeAvailableSort('ds_created');
  $query->removeAvailableSort('score');
  $query->setAvailableSort('score', array('title' => t('Relevance'), 'default' => 'desc'));
  $query->setAvailableSort('ds_changed', array('title' => t('Last updated'), 'default' => 'desc'));
}

function get_search_types(){
  return array(
  'app' => t('Apps'),
  'blog' => t('Blogs'),
  'forum' => t('Forum Posts'),
  'resource' => t('Library'),
  'dataset_request'  => t('Dataset Requests'),
  'page' => t('Pages'),
  'book' => t('Books'),
  );
}


/**
 * Implements hook_ctools_plugin_directory().
 */
function dgu_search_ctools_plugin_directory($module, $plugin) {
    if ($module == 'ctools' && !empty($plugin)) {
        return "plugins/$plugin";
    }
}


// Implements hook_block_info().
function dgu_search_block_info() {
  $blocks = array();
  $search_types = array(
    'app' => t('Apps'),
    'blog' => t('Blogs'),
    'forum' => t('Forum Posts'),
    'resource' => t('Library'),
    'dataset_request'  => t('Dataset Requests'),
  );

  // Create a block for each content type to search in solr.
  foreach ($search_types as $search_type => $type) {
    $blocks['search' . $search_type] = array(
      'info' => t('Search ' . $type),
    );
  }

  return $blocks;
}


// Implements hook_block_view().
function dgu_search_block_view($delta = '') {
  // Get the search type from delta.
  $search_type = substr($delta, 6);

  // Add the search type into the form state so form can be form_altered correctly.
  $form_state = array(
    'searchtype' => $search_type,
  );
  $search_types = array(
        'app' => t('Apps'),
        'blog' => t('Blogs'),
        'forum' => t('Forum Posts'),
        'resource' => t('Library'),
        'dataset_request'  => t('Dataset Requests'),
  );

  $searchform = drupal_build_form('search_block_form', $form_state);

  $block['subject'] = t('Search '. $search_types[$search_type]);
  $block['content'] = $searchform;

  return $block;
}


// Implements hook_form FORM_ID_alter().
function dgu_search_form_search_block_form_alter(&$form, &$form_state, $form_id) {

  // Add custom form submition so we can redirect.
  $form['#submit'][] = 'dgu_search_form_search_block_form_submit';

  $form['#attributes']['class'][] = 'form-search';
  if (isset($form_state['searchtype'])) {
    // Add a variable into the form so we can redirect to correct solr search on submit.
    $form['searchtype'] = array(
      '#type' => 'hidden',
      '#value' => $form_state['searchtype'],
    );

    // Add settings for apachesolr_autocomplete's patch to enable filtering by custom search.
    $form['#search_page']['page_id'] = 'search_' . $form_state['searchtype'];
  }

}


/**
 * Implement HOOK_forms
 *
 * @return array of forms
 */
function dgu_search_forms() {
  $forms['dgu_search_form'] = array(
    'callback' => 'dgu_search_search_block',
  );
  return $forms;
}

function dgu_search_search_block($form, &$form_state) {
  $form['search_block_form'] = array(
    '#type' => 'textfield',
    '#title' => t('Search'),
    '#title_display' => 'invisible',
    '#size' => 15,
    '#default_value' => '',
    '#attributes' => array('title' => t('Enter the terms you wish to search for.')),
  );
  if (isset($form_state['dataset_request_count'])){
    $form['dataset_request_count']= array(
      '#type' => 'hidden',
      '#value' => $form_state['dataset_request_count'],
    );
  }
  $form['content_type'] = array(
    '#type' => 'hidden',
    '#value' => $form_state['content_type'],
  );
  $form['searchtype'] = array(
    '#type' => 'hidden',
    '#value' => $form_state['searchtype'],
  );
  $form['count'] = array(
    '#type' => 'hidden',
    '#value' => $form_state['count'],
  );
  $form['f'] = array(
    '#type' => 'value',
    '#value' => $form_state['f'],
  );
  $form['actions'] = array('#type' => 'actions');
  $form['actions']['submit'] = array('#type' => 'submit', '#value' => t('Search'));
  $form['#submit'] = array('dgu_search_form_search_block_form_submit');
  $form['#theme'] = 'dgu_search_form';
  return $form;
}


function dgu_search_menu_breadcrumb_alter(&$active_trail, $item){
  $env_id = variable_get('apachesolr_default_environment', 'solr');
  if (apachesolr_has_searched($env_id)) {
    drupal_set_title("Search");
    $query = apachesolr_current_query($env_id);
    $fq = $query->getParam('fq');
    foreach ($fq as $string){
      $name = '';
      if (strstr($string, ':')) {
        list($name, $value) = explode(":", $string, 2);
      }
      if ($name == 'bundle'){
        $search_types = get_search_types();
        $form_state['content_type'] = $search_types[$value];
        $form_state['searchtype'] = $value;



        $active_trail = array_slice($active_trail, 0, 1);
        $active_trail[] = array('title' => t('Search'), 'href' => 'search/everything', 'localized_options' => array());
        //need it in twice because the last item gets removed.
        $active_trail[] = array('title' => t('Search'), 'href' => 'search/everything', 'localized_options' => array());
        drupal_set_title($search_types[$value]);
        break;
      }
    }
  }

}

/**
 * Added form submit function to retain filters.
 *
 * @see apachesolr_search_form_search_submit()
 */
function dgu_search_form_search_block_form_submit($form, &$form_state) {
  $fv = $form_state['values'];
  $form_state['values']['search_block_form'] = $fv['search_block_form'];
  $form_state['values']['dgu_search_form'] = $fv['search_block_form'];
  search_box_form_submit($form, $form_state);

  $search_types = array(
      'app' => t('Apps'),
      'blog' => t('Blogs'),
      'forum' => t('Forum Posts'),
      'resource' => t('Library'),
      'dataset_request'  => t('Dataset Requests'),
  );

  if (isset($fv['search_block_form'])) {
    $facets = '';
    if (isset($fv['searchtype']) && !empty($search_types[$fv['searchtype']])) {
      $facets =  "?f[0]=bundle%3A" . $fv['searchtype'];
    }
    if (!empty($fv['f'])) {
      if (!empty($facets)){
        $facets .= '&';
      } else {
        $facets = '?';
      }
      foreach($fv['f'] as $i => $facet){
        $facets .= 'f[' . $i . ']=' . $facet . '&';
      }
    }

    // Replace keys with their rawurlencoded value
    $raw_keys = str_replace("/","%2f",$fv['search_block_form']);

    // Override redirect with a new bundle specific search.
    global $base_url;
    $form_state['redirect'] =  $base_url."/search/everything/" . $raw_keys . $facets;
  }
}


/**
 * @param $form
 * @return the altered form
 *
 * Remove the retain-filters element added to the search form by apachesolr_panels
 *
 */
function dgu_search_hide_retain_filters(&$form){
    unset($form['basic']['retain-filters']);
    return $form;
}

/**
 * @param $form
 * @param $form_state
 * @param $form_id
 *
 * Implement Hook hook_form_FORM_ID_alter which creates our own hidden retain filters input and
 * sets up an after build hook to remove the one provided by apachesolr_panels
 *
 */
function dgu_search_form_apachesolr_panels_search_form_alter(&$form, &$form_state, $form_id){
    $form['dgu']['retain-filters'] = array(
        '#type' => 'hidden',
        '#title' => t('Retain current filters'),
        '#value' => 1,
    );
    $form['#after_build'] = array('dgu_search_hide_retain_filters');
}

/**
 * Implements hook_query_alter().
 */
function dgu_search_apachesolr_query_alter($query) {
  // Retrieve 'field_developed_by'.
  $query->addParam('fl', 'sm_field_developed_by');
  // Retrieve 'field_review_status'.
  $query->addParam('fl', 'im_field_review_status');
}


/**
 * Implements hook_facetapi_searcher_info()
 */
function dgu_search_facetapi_searcher_info_alter(array &$searcher_info) {
  foreach ($searcher_info as $key => $value) {
    if($value['url processor'] == 'standard'){
      $searcher_info[$key]['url processor'] = 'dgu_search_url_processor';
    }
  }
}

/**
 * Implements hook_facetapi_url_processors().
 */
function dgu_search_facetapi_url_processors() {
  return array(
    'dgu_search_url_processor' => array(
      'handler' => array(
        'label' => t('DGU Search Facet Api URL processor'),
        'class' => 'FacetApiDguSearch',
      ),
    ),
  );
}

class FacetApiDguSearch extends FacetapiUrlProcessorStandard {
  public function setBreadcrumb() {
    // Override method so bread crumb is not altered.
  }
}
