<?php
/**
 * @file
 * dgu_site_feature.panels_default.inc
 */

/**
 * Implements hook_default_panels_mini().
 */
function dgu_site_feature_default_panels_mini() {
  $export = array();

  $mini = new stdClass();
  $mini->disabled = FALSE; /* Edit this to true to make a default mini disabled initially */
  $mini->api_version = 1;
  $mini->name = 'what_s_data_gov_uk_all_about_';
  $mini->category = 'Mini Panels';
  $mini->admin_title = 'What\'s data.gov.uk all about?';
  $mini->admin_description = '';
  $mini->requiredcontexts = array();
  $mini->contexts = array();
  $mini->relationships = array();
  $display = new panels_display();
  $display->layout = 'onecol';
  $display->layout_settings = array();
  $display->panel_settings = array(
    'style_settings' => array(
      'default' => NULL,
      'middle' => NULL,
    ),
  );
  $display->cache = array();
  $display->title = 'What\'s data.gov.uk all about?';
  $display->content = array();
  $display->panels = array();
    $pane = new stdClass();
    $pane->pid = 'new-1';
    $pane->panel = 'middle';
    $pane->type = 'custom';
    $pane->subtype = 'custom';
    $pane->shown = TRUE;
    $pane->access = array();
    $pane->configuration = array(
      'admin_title' => '',
      'title' => '',
      'body' => '<p>Hear more about the Government\'s Transparency agenda from the Prime Minister.</p><p><iframe width="220" height="240" src="http://www.youtube.com/embed/0stXV_fWWtU?wmode=transparent&rel=0" frameborder="0" allowfullscreen></iframe></p>',
      'format' => 'full_html',
      'substitute' => TRUE,
    );
    $pane->cache = array();
    $pane->style = array(
      'settings' => NULL,
    );
    $pane->css = array();
    $pane->extras = array();
    $pane->position = 0;
    $pane->locks = array();
    $display->content['new-1'] = $pane;
    $display->panels['middle'][0] = 'new-1';
  $display->hide_title = PANELS_TITLE_FIXED;
  $display->title_pane = 'new-1';
  $mini->display = $display;
  $export['what_s_data_gov_uk_all_about_'] = $mini;

  return $export;
}
