<?php
/**
 * @file
 * Code for the DGU Forum feature.
 */

define('PUBLISHED_FORUM_GRANT', 2147483647);    // maximum possible value (avialable in Solr) to avoid conflict with $node->uid
define('FORUM_MODERATOR_GRANT', 2147483646); // maximum possible value (avialable in Solr) -1 to avoid conflict with $node->uid

include_once 'dgu_forum.features.inc';

function dgu_forum_node_access_records($node) {
  if (($node->type == 'forum')) {
    $grants = array();

    $grants[] = array(
      'realm' => 'forum',
      'gid' => FORUM_MODERATOR_GRANT,
      'grant_view' => 1,
      'grant_update' => 1,
      'grant_delete' => 1,
    );
    $grants[] = array(
      'realm' => 'forum',
      'gid' => $node->uid,
      'grant_view' => 1,
      'grant_update' => 1,
      'grant_delete' => 1,
    );
    if ($node->status == 1) {
      $grants[] = array(
        'realm' => 'forum',
        'gid' => PUBLISHED_FORUM_GRANT,
        'grant_view' => 1,
        'grant_update' => 0,
        'grant_delete' => 0,
      );
    }
    return $grants;
  }
}

function dgu_forum_node_grants($account, $op) {
  $grants = array();
  $grants['forum'] = array($account->uid);
  $grants['forum'] = array($account->uid, PUBLISHED_FORUM_GRANT);
  if (user_access('edit any forum content', $account)) {
    $grants['forum'] = array(FORUM_MODERATOR_GRANT);
  }
  return $grants;
}
