<?php
/**
 * @file
 * Code for the DGU Forum feature.
 */

define('FORUM_MODERATION_PERMISSION', 'edit any forum content');

include_once 'dgu_forum.features.inc';

function dgu_forum_dgu_moderation_moderator_permission(&$node) {
  if ($node->type == 'forum') {
    return user_access(FORUM_MODERATION_PERMISSION);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function dgu_forum_form_forum_node_form_alter(&$form, &$form_state, $form_id) {

  drupal_set_title(t('Create forum topic'));
  unset($form['actions']['preview']);
  $form['#attributes']['class'][] = "boxed";

  dgu_moderation_node_forms_alter($form, FORUM_MODERATION_PERMISSION);
}

function dgu_forum_node_access($node, $op, $account) {
  if ($op != 'create' && $node->type == 'forum') {
    return dgu_moderation_access($account, $node, FORUM_MODERATION_PERMISSION);
  }
}

function dgu_forum_node_access_records($node) {
  if (($node->type == 'forum')) {
    return dgu_moderation_get_node_grants($node);
  }
}

function dgu_forum_node_grants($account, $op) {
  return dgu_moderation_get_account_grants($account, FORUM_MODERATION_PERMISSION);
}