<?php

/**
 * @file
 * Code for the DGU Services feature.
 */
include_once 'dgu_services.features.inc';

/**
 * Implements hook_menu().
 */
function dgu_services_menu() {
  $items = array();

  $items['comment/dataset/%'] = array(
    'page callback' => 'dgu_services_add_reply',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['comment/issue/%'] = array(
    'page callback' => 'dgu_services_add_issue_reply',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['comment/get/%'] = array(
    'page callback' => 'dgu_services_get_replies',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['comment/issue/get/%'] = array(
    'page callback' => 'dgu_services_get_issue_replies',
    'page arguments' => array(3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_services_resources().
 */
function dgu_services_services_resources() {
 $session_resource = array(
    'session' => array(
      'operations' => array(
        'retrieve' => array(
          'callback' => 'dgu_services_session_get',
          'args' => array(
            array(
              'name' => 'sid',
              'optional' => FALSE,
              'source' => array('data' => 'sid'),
              'type' => 'string',
              'description' => 'Session ID',
            ),
          ),
          'access callback' => 'dgu_services_session_access',
        ),

      ),
    ),
  );
  return $session_resource;
}

// TODO check security
function dgu_services_session_access() {
  return TRUE;
}

function dgu_services_session_get($sid = null) {

// That was in D6, not sure if it's necessary
//  global $user;
//  if (!$sid) {
//    $sid = $user->sid;
//  }

  return db_select('sessions', 's')
    ->fields('s', array('uid'))
    ->condition('sid', $sid)
    ->execute()
    ->fetchField();
}

function dgu_services_add_reply($ckan_id) {
  if ($dataset = dgu_services_get_dataset_from_ckan_id($ckan_id)) {
    $instance = field_info_instance('ckan_dataset', 'field_comment', 'ckan_dataset');

    // Return a link.
    $href = '/reply/add/' . $dataset->id . '/' . $instance['id'] . '/0';
    if(user_is_logged_in()) {
      return '<a href="' . $href. '">Add reply</a>';
    }
    else {
      return '<a href="/user/login?destination=' . $href . '">Log in</a> or <a href="/user/register?destination=' . $href . '">register</a> to post a reply';
    }

    //drupal_goto('reply/add/' . $dataset->id . '/' . $instance['id'] . '/0' , array()); // Alternatively return rendered form.
  }
}

function dgu_services_get_replies($ckan_id) {
  if ($dataset = dgu_services_get_dataset_from_ckan_id($ckan_id)) {

    // Not sure if this is necessary.
    //field_attach_prepare_view('ckan_dataset', array($dataset->id => $dataset), 'comment');


    $output = field_attach_view('ckan_dataset', $dataset, 'default');
    if (isset($output['field_comment'][0]['#markup'])) {

      $rendered_output = flag_create_link('subscribe_dataset_update', $dataset->id);
      $rendered_output .= flag_create_link('subscribe_dataset_comment', $dataset->id);
      // Display 'Comemnts' heading only if at least one reply exist (testing if CSS class 'push' exist in the markup).
      if (strpos($output['field_comment'][0]['#markup'], 'push') !== FALSE) {
        $rendered_output .= '<div class="replies-header"><h3>Comments</h3></div>';
      }

      $rendered_output .= $output['field_comment'][0]['#markup'];
      // Fix flag on replies on ckan side so user is redirected back to a dataset vie page instead of drupal api endpoint
      $rendered_output = str_replace('destination=comment/get', 'destination=dataset', $rendered_output);



      print $rendered_output;
      // Update the history table, stating that this user viewed this dataset.
      ckan_dataset_tag_new($dataset);
      drupal_exit();
    }
  }
  drupal_not_found();
}

function dgu_services_get_dataset_from_ckan_id($ckan_id) {
  for ($tries = 10; $tries > 0; $tries--) {
    if ($dataset_id = dgu_services_get_dataset_id_from_ckan_id($ckan_id)) {
      return ckan_dataset_load($dataset_id);
    }
    else {
      // A dataset with this id doesn't exist in Drupal.
      // Syncing from CKAN on the fly.
      module_load_include('inc', 'ckan', 'ckan.drush');
      $client = ckan_get_client();

      try {
        $dataset = $client->GetDataset(array('id'=>$ckan_id))->toArray();
        return ckan_synchronise_dataset($dataset['result']);
      }
      catch (Exception $e) {
        watchdog('comment_get', 'Error synchronising dataset ' . $ckan_id, array(), WATCHDOG_ERROR);
      }
    }
  }
}

function dgu_services_get_dataset_id_from_ckan_id($ckan_id) {
  $query = new EntityFieldQuery();
  $result = $query->entityCondition('entity_type', 'ckan_dataset')->propertyCondition('ckan_id', $ckan_id)->execute();
  if (isset($result['ckan_dataset'])) {
    $keys = array_keys($result['ckan_dataset']);
    return array_shift($keys);
  }
}

function dgu_services_add_issue_reply($id) {
  if (!empty($id) && is_numeric($id)) {
    $issue = ckan_issue_load($id);
    if (!$issue) {
      // An issue with this id doesn't exist in Drupal.
      // Syncing from CKAN on the fly.
      module_load_include('inc', 'ckan', 'ckan.drush');
      $client = ckan_get_client();

      try {
        ckan_resync_issues();
      }
      catch (Exception $e) {
        watchdog('comment_issue_get', 'Error synchronising issue ' . $id, array(), WATCHDOG_ERROR);
        drupal_exit();
      }

      $issue = ckan_issue_load($id);
      if (!$issue) {
        watchdog('comment_issue_get', 'Unable to synchronise issue ' . $id, array(), WATCHDOG_ERROR);
        drupal_not_found();
        return;
      }
    }

    $instance = field_info_instance('ckan_issue', 'field_comment', 'ckan_issue');

    // Return a link.
    $href = '/reply/add/' . $id . '/' . $instance['id'] . '/0';
    if(user_is_logged_in()) {
      return '<a href="' . $href. '">Add reply</a>';
    }
    else {
      return '<a href="/user/login?destination=' . $href . '">Log in</a> or <a href="/user/register?destination=' . $href . '">register</a> to post a reply';
    }
  }
}

function dgu_services_get_issue_replies($id) {
  if ($issue = ckan_issue_load($id)) {

    $output = field_attach_view('ckan_issue', $issue, 'default');
    if (isset($output['field_comment'][0]['#markup'])) {

      // TODO add issue flags.
      $rendered_output='';
//      $rendered_output = flag_create_link('subscribe_dataset_update', $issue->id);
//      $rendered_output .= flag_create_link('subscribe_dataset_comment', $issue->id);

      // Display 'Comemnts' heading only if at least one reply exist (testing if CSS class 'push' exist in the markup).
      if (strpos($output['field_comment'][0]['#markup'], 'push') !== FALSE) {
        $rendered_output .= '<div class="replies-header"><h3>Comments</h3></div>';
      }

      $rendered_output .= $output['field_comment'][0]['#markup'];
//      // Fix flag on replies on ckan side so user is redirected back to an issue via page instead of drupal api endpoint
//      $rendered_output = str_replace('destination=comment/get', 'destination=dataset', $rendered_output);



      print $rendered_output;
      // Update the history table, stating that this user viewed this issue.
      ckan_issue_tag_new($issue);
      drupal_exit();
    }
  }
  drupal_not_found();
}

function dgu_services_form_reply_add_form_alter(&$form, $form_state, $form_id) {
  if (substr($form['redirect']['#value'], 0, 12) == 'ckan_dataset') {
    $drupal_dataset_id = substr($form['redirect']['#value'], 13);
    $dataset = entity_load_single('ckan_dataset', $drupal_dataset_id);
    $form['redirect']['#value'] = 'dataset/' . $dataset->name;
  }
}

// Expose email address for everbody, work around on services_remove_user_data() which requires 'administer users' role to get email
function dgu_services_services_account_object_alter(&$account) {
  $account = user_load($account->uid, TRUE);
  unset($account->pass);
}