<?php
/**
 * @file
 * Drupal needs this blank file.
 */

include_once 'dgu_app.features.inc';

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 * Add boxed class and change page title on app node form.
 */
function dgu_app_form_node_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'app_node_form') {
    $form['#attributes']['class'][] = 'boxed';
    drupal_set_title(t('Submit an app'));
  }
}
/**
 * Implements hook_form_FORM_ID_alter().
 */
function dgu_app_form_app_node_form_alter(&$form, &$form_state, $form_id) {

  $form['revision_information']['#type'] = 'hidden';

  $form['actions']['publish']['#access'] = TRUE;
  $form['actions']['publish']['#value'] = 'Submit for moderation';
  $form['actions']['publish']['#type'] = 'submit';
  $form['actions']['publish']['#weight'] = 6;
  $form['actions']['publish']['#submit'] = $form['actions']['submit']['#submit'];

  $form['actions']['submit']['#value'] = 'Save draft';
  $form['#submit'][] = 'dgu_app_node_submit';

  unset($form['actions']['preview']);
}

/**
 * Custom submit function for challenge content type.
 */
function dgu_app_node_submit($form, &$form_state) {
  if(isset($form_state['clicked_button'])) {

    $action = empty($form['#node']->nid) ? 'created' : 'updated';

    if ($form_state['clicked_button']['#value'] == "Submit for moderation") {
      $form_state['values']['workbench_moderation_state_new'] = 'needs_review';
      $message = &drupal_static(__FUNCTION__, NULL);
      $message = 'Your App has been ' . $action . ' and submitted for moderation. Login to your <a href="/admin/workbench">profile</a> to update it. You can submit this now or later';
    }
    elseif ($form_state['clicked_button']['#value'] == "Save draft") {
      $form_state['values']['workbench_moderation_state_new'] = 'draft';
      $message = &drupal_static(__FUNCTION__, NULL);
      $message = 'Your draft App has been ' . $action . '. Login to your <a href="/admin/workbench">profile</a> to update it. You can submit this now or later';
    }
  }
}

function dgu_app_exit() {
  if ($message = &drupal_static('dgu_app_node_submit', NULL)) {
    // Remove all status messages - most likely nothing more than '... has been created/updated'
    drupal_get_messages('status');
    // Add a message created in dgu_data_set_request_node_submit()
    drupal_set_message($message);
  }
}