<?php
/**
 * @file
 * Code for the DGU Data set request feature.
 */


define('DATA_REQUEST_MODERATION_PERMISSION', 'edit any dataset_request content');
define('PUBLIC_DATA_REQUEST_GRANT', 2147483647);    // maximum possible value (avialable in Solr) to avoid conflict with $node->uid
define('DATA_REQUEST_MODERATOR_GRANT', 2147483646); // maximum possible value (avialable in Solr) -1 to avoid conflict with $node->uid
define('DATA_REQUEST_CKAN_ADMIN_GRANT', 2147483645); // maximum possible value (avialable in Solr) -2 to avoid conflict with $node->uid

include_once 'dgu_data_set_request.features.inc';

/*
 * Implements hook_ctools_plugin_directory().
 */
function dgu_data_set_request_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && !empty($plugin)) {
    return "plugins/$plugin";
  }
}

/**
 * Implements hook_libraries_info_file_paths().
 */
function dgu_data_set_request_libraries_info_file_paths() {
  $d3_libraries = drupal_get_path('module', 'dgu_data_set_request') . '/libraries/';
  foreach (dgu_data_set_request_d3_libraries() as $library) {
    $paths[] = $d3_libraries . $library;
  }
  return $paths;
}

/**
 * Implements hook_libraries_info_alter().
 */
function dgu_data_set_request_libraries_info_alter(&$libraries) {
  $path = drupal_get_path('module', 'dgu_data_set_request') . '/libraries/';
  foreach (dgu_data_set_request_d3_libraries() as $library) {
    // Change library path to path/to/module/d3/libraries
    $libraries[$library]['library path'] = $path . $library;
  }
}

/**
 * Helper callback to return all d3 libraries located inside this module.
 */
function dgu_data_set_request_d3_libraries() {
  $module_path = drupal_get_path('module', 'dgu_data_set_request');
  $d3_libraries = str_replace($module_path . '/libraries/', '', glob($module_path . '/libraries/*' , GLOB_ONLYDIR));
  return $d3_libraries;
}

/**
 * Implements hook_dgu_moderation_moderator_permission().
 */
function dgu_data_set_request_dgu_moderation_moderator_permission(&$node) {
  if ($node->type == 'dataset_request') {
    if (user_access(DATA_REQUEST_MODERATION_PERMISSION) || is_or_was_assignee($node->nid)) {
      return TRUE;
    }
  }
}

/**
 * Implements hook_menu_breadcrumb_alter().
 */
function dgu_data_set_request_menu_breadcrumb_alter(&$active_trail, $item) {
  switch ($item['path']) {
    case 'data-request':
      $active_trail = array(
        current($active_trail),
        array('title' => 'Data Requests', 'href' => 'data-request', 'localized_options' => array()),
        array('title' => 'Data Requests', 'href' => 'data-request', 'localized_options' => array()),
      );
      drupal_set_title('Latest data requests');
      break;
    case 'data-request/blogs':
      $active_trail = array(
        current($active_trail),
        array('title' => 'Data Requests', 'href' => 'data-request', 'localized_options' => array()),
      );
      drupal_set_title('ODUG Blogs');
      break;
    case 'data-request/minutes':
      $active_trail = array(
        current($active_trail),
        array('title' => 'Data Requests', 'href' => 'data-request', 'localized_options' => array()),
      );
      drupal_set_title('ODUG Minutes');
      break;
  }
  if (isset($item['map'][1]->type) && $item['map'][1]->type == 'dataset_request') {
    $active_trail[2] = $active_trail[1];
    $active_trail[1] = array('title' => 'Data Requests', 'href' => 'data-request', 'localized_options' => array());

    if (isset($item['map'][2]) && $item['map'][2] == 'edit') {
      unset($active_trail[2]);
    }

  }
}


/**
 * Implements Hook hook_form_FORM_ID_alter which:
 */
function dgu_data_set_request_form_dataset_request_node_form_alter(&$form, &$form_state, $form_id) {
  $node = $form['#node'];
  drupal_set_title('Create a dataset request');
  unset($form['actions']['preview']);
  $form['#attributes']['class'][] = "boxed";

  if (user_access(DATA_REQUEST_MODERATION_PERMISSION) || (isset($node->nid) && is_or_was_assignee($node->nid))) {
    $form['#after_build'][] = 'dgu_moderation_node_forms_after_build';
    $form['#after_build'][] = 'dgu_data_set_request_existing_title_disable_maxlength';

    $form['submit_top'] = $form['actions']['submit'];
    $form['submit_top']['#weight'] = -100;
    $form['#attached']['css'][] = array(
      'data' => '#edit-submit-top {float: right;}',
      'type' => 'inline',
    );
    $assignee_uids = dgu_data_set_request_get_assignees($node->nid);
    $assignees = array();
    foreach($assignee_uids as $uid) {
      $user = user_load($uid);
      if (empty($form['field_assignee'][LANGUAGE_NONE]['#default_value'][0]) || isset($form['field_assignee'][LANGUAGE_NONE]['#default_value'][0]) && $form['field_assignee'][LANGUAGE_NONE]['#default_value'][0] != $user->uid) {
        $assignees[] = $user->name;
      }
    }
    if(!empty($assignees)) {
      $assignees = '<div class="help-block">Previous RM\'s: ' . implode(', ', $assignees) . '</div>';
      $form['field_assignee']['#suffix'] = $assignees;
    }
  }

  else {
    dgu_moderation_node_forms_alter($form);
  }

  $form['#validate'][] = 'dgu_data_set_request_form_validate';
  $form['#submit'][] = 'dgu_data_set_request_form_submit';
}

function dgu_data_set_request_existing_title_disable_maxlength($form, &$form_state) {
  global $user;
  if (in_array('data request administrator', $user->roles) || in_array('editor', $user->roles)) {
    unset($form['title']['#maxlength']);
    $form['title']['#maxlength_js'] = FALSE;
  }
  return $form;
}

function dgu_data_set_request_form_validate($form, &$form_state) {
  if (isset($form_state['values']['field_review_outcome'][LANGUAGE_NONE][0]['value']) && ($form_state['values']['field_review_outcome'][LANGUAGE_NONE][0]['value'] == '0' || $form_state['values']['field_review_outcome'][LANGUAGE_NONE][0]['value'] == 2)) {
    if(empty($form_state['values']['field_data_set_link'][LANGUAGE_NONE][0]['url'])) {
      form_set_error('field_organisation_type', 'Dataset link field is required.');
    }
  }
}

function dgu_data_set_request_form_submit($form, &$form_state) {
  if (isset($form_state['values']['field_review_status'][LANGUAGE_NONE][0]['value']) && ($form_state['values']['field_review_status'][LANGUAGE_NONE][0]['value'] != '6')) {
    // Empty outcome field if a request is re-opened.
    $form_state['node']->field_review_outcome = array();
  }
}

function dgu_data_set_request_get_assignees($nid) {
  $assignees = &drupal_static(__FUNCTION__);
  if (empty($assignees)) {
    $query = db_select('field_revision_field_assignee', 'fpa')
      ->distinct()
      ->fields('fpa', array('field_assignee_uid'))
      ->condition('entity_type', 'node')
      ->condition('entity_id', $nid);
    $assignees = $query->execute()->fetchCol();
  }
  return $assignees;
}

function dgu_data_set_request_node_access($node, $op, $account) {
  if ($op != 'create' && $node->type == 'dataset_request') {
    if(!($node->uid == $account->uid || user_access(DATA_REQUEST_MODERATION_PERMISSION))) {
      if(isset($node->field_publication_preference[LANGUAGE_NONE][0]['value']) && $node->field_publication_preference[LANGUAGE_NONE][0]['value'] == 0) {
        if(isset($node->field_publisher_ref[LANGUAGE_NONE][0]['id']) && isset($account->data['ckan_publishers'][$node->field_publisher_ref[LANGUAGE_NONE][0]['id']]) && $account->data['ckan_publishers'][$node->field_publisher_ref[LANGUAGE_NONE][0]['id']] == 'admin') {
          return NODE_ACCESS_ALLOW;
        }
        $assignees = dgu_data_set_request_publisher_assignee_get_assignees($node->nid);
        if(!in_array($account->uid, $assignees)) {
          return NODE_ACCESS_DENY;
        }

      }
    }
  }
}

function dgu_data_set_request_node_access_records($node) {
  if ($node->type == 'dataset_request') {

    $assignees = dgu_data_set_request_publisher_assignee_get_assignees($node->nid);

    $grants = array();
    if (isset($node->field_publication_preference[LANGUAGE_NONE][0]['value']) && $node->field_publication_preference[LANGUAGE_NONE][0]['value'] == 0) {
      // Private request
      $grants[] = array(
        'realm' => 'private_data_request',
        'gid' => DATA_REQUEST_MODERATOR_GRANT,
        'grant_view' => 1,
        'grant_update' => 1,
        'grant_delete' => 1,
        'priority' => 1,
      );
      $grants[] = array(
        'realm' => 'private_data_request',
        'gid' => DATA_REQUEST_CKAN_ADMIN_GRANT,
        'grant_view' => 1,
        'grant_update' => 0,
        'grant_delete' => 0,
        'priority' => 1,
      );
      if ($node->uid) {
        // Grant author permission only if author is not anonymous.
        $grants[] = array(
          'realm' => 'private_data_request',
          'gid' => $node->uid,
          'grant_view' => 1,
          'grant_update' => 1,
          'grant_delete' => 1,
          'priority' => 1,
        );
      }
      if (!empty($assignees)) {
        // Grant permission to all users which are or were assignees in this request.
        foreach($assignees as $assignee_uid) {
          $grants[] = array(
            'realm' => 'private_data_request',
            'gid' => $assignee_uid,
            'grant_view' => 1,
            'grant_update' => 0,
            'grant_delete' => 0,
            'priority' => 1,
          );
        }
      }
    }
    else {
      // Public request
      $grants[] = array(
        'realm' => 'public_data_request',
        'gid' => DATA_REQUEST_MODERATOR_GRANT,
        'grant_view' => 1,
        'grant_update' => 1,
        'grant_delete' => 1,
        'priority' => 1,
      );
      if ($node->uid) {
        // Grant author permission only if author is not anonymous.
        $grants[] = array(
          'realm' => 'public_data_request',
          'gid' => $node->uid,
          'grant_view' => 1,
          'grant_update' => 1,
          'grant_delete' => 1,
          'priority' => 1,
        );
      }
      if (!empty($assignees)) {
        // Grant permission to all users which are or were assignees in this request.
        foreach($assignees as $assignee_uid) {
          $grants[] = array(
            'realm' => 'public_data_request',
            'gid' => $assignee_uid,
            'grant_view' => 1,
            'grant_update' => 0,
            'grant_delete' => 0,
            'priority' => 1,
          );
        }
      }
      if ($node->status == 1) {
        $grants[] = array(
          'realm' => 'public_data_request',
          'gid' => PUBLIC_DATA_REQUEST_GRANT,
          'grant_view' => 1,
          'grant_update' => 0,
          'grant_delete' => 0,
          'priority' => 1,
        );
      }
    }
    return $grants;
  }
}

function dgu_data_set_request_node_grants($account, $op) {
  $grants = array();
  $grants['private_data_request'] = array($account->uid);
  $grants['public_data_request'] = array($account->uid, PUBLIC_DATA_REQUEST_GRANT);
  if (user_access(DATA_REQUEST_MODERATION_PERMISSION, $account)) {
    $grants['private_data_request'] = array(DATA_REQUEST_MODERATOR_GRANT);
    $grants['public_data_request'] = array(DATA_REQUEST_MODERATOR_GRANT);
  }
  if (!empty($account->data['ckan_publishers']) && in_array('admin', $account->data['ckan_publishers'])) {
    $grants['private_data_request'][] = DATA_REQUEST_CKAN_ADMIN_GRANT;
  }
  return $grants;
}


/**
 * Implements hook_assignee_get_users().
 */
function dgu_data_set_request_assignee_get_users($field = NULL, $instance = NULL, $entity_type = NULL, $entity) {

  $query = db_select('role', 'r');
  $query->join('users_roles', 'ur', 'r.rid = ur.rid');
  $query->join('users', 'u', 'u.uid = ur.uid');
  $query->fields('ur', array('uid'))
        ->fields('u', array('name'))
        ->condition('r.name', 'data request administrator');
  $users = $query->execute()->fetchAll();

  $options = array();
  foreach ($users as $user) {
    $options[$user->uid] = $user->name;
  }

  return $options;
}

/**
 * Implements hook_node_presave().
 */
function dgu_data_set_request_node_presave($node) {
  if ($node->type == 'dataset_request') {
    $previous_data_request_revision = &drupal_static('previous_data_request_revision');

    // Workbench moderation uses shutdown function to update the node for the second time in the same request.
    // To avoid messages being created twice we ignore second node update in single request.
    if (isset($previous_data_request_revision)) {
      $updates_to_ignore = &drupal_static('node_updates_to_ignore');
      $updates_to_ignore = isset($updates_to_ignore) ? $updates_to_ignore : array();
      $updates_to_ignore[] = $node->nid;
    }

    // Store previous revision of the node in static cache to be available for comparison in hook_node_update().
    $previous_data_request_revision = node_load($node->nid);
  }
}

/**
 * Implements hook_entity_insert().
 */
function dgu_data_set_request_entity_insert($entity, $type) {
  if($type == 'reply' && $entity->bundle == 'review_comment' && module_exists('message_subscribe')) {
    // This is taken from message stack examples.
    // It's related to message_notify how it stores rendered subject and body via view modes.
    $options = array(
      'rendered fields' => array(
        'message_notify_email_subject' => 'field_message_rendered_subject',
        'message_notify_email_body' => 'field_message_rendered_body',
      ),
    );
    $data_request_admin_roles = variable_get('dgu_data_set_request_data_request_admin_roles',array(3, 6, 10)); // 3 = administrator, 6 = data publisher, 10 = data request administrator

    // Get data_request_update message bundle and set required fields.
    $message = message_create('data_request_review_comment_new');
    $wrapper = entity_metadata_wrapper('message', $message);
    $data_request_node = node_load($entity->entity_id);
    $wrapper->field_data_request_reference->set($data_request_node);
    $wrapper->field_reply_reference->set($entity);

    $uids = _dgu_data_set_request_get_subscribers($data_request_node->nid, $data_request_admin_roles, FALSE);
    message_subscribe_send_message('node', $data_request_node, $message, $options, array('uids' => $uids));

  }
}

/**
 * Implements hook_node_update().
 */
function dgu_data_set_request_node_update($node) {
  if ($node->type == 'dataset_request' && module_exists('message_subscribe')) {

    // Ignore second node update in single request.
    // See dgu_data_set_request_node_presave();
    $updates_to_ignore = &drupal_static('node_updates_to_ignore');
    if (is_array($updates_to_ignore) && in_array($node->nid, $updates_to_ignore)) {
      return;
    }

    // Don't create a message about moderation here, there should be
    // an universal message about moderation state change for all content types.
    if (empty($node->workbench_moderation_state_current) && $node->workbench_moderation['current']->from_state == 'needs_review' && $node->workbench_moderation['current']->state == 'published'
      || $node->workbench_moderation['current']->from_state == 'needs_review' && $node->workbench_moderation['current']->state == 'draft') {
      return;
    }

    $previous_data_request_revision = &drupal_static('previous_data_request_revision');
    $previous_rm = isset($previous_data_request_revision->field_assignee[LANGUAGE_NONE][0]['uid']) ? $previous_data_request_revision->field_assignee[LANGUAGE_NONE][0]['uid'] : NULL;
    $previous_publisher_assignee = isset($previous_data_request_revision->field_publisher_assignee[LANGUAGE_NONE][0]['uid']) ? $previous_data_request_revision->field_publisher_assignee[LANGUAGE_NONE][0]['uid'] : NULL;

    $fields_for_short_summary = array('field_review_status' => 'value', 'field_review_outcome' =>'value', 'field_review_notes' => 'value');
    $data_request_admin_roles = variable_get('dgu_data_set_request_data_request_admin_roles',array(3, 6, 10, 12)); // 3 = administrator, 6 = data publisher, 10 = data request administrator, 12 = editor

    // This is taken from message stack examples.
    // It's related to message_notify how it stores rendered subject and body via view modes.
    $options = array(
      'rendered fields' => array(
        'message_notify_email_subject' => 'field_message_rendered_subject',
        'message_notify_email_body' => 'field_message_rendered_body',
      ),
    );

    // Use static cache to get this summary available in hook_tokens().
    $summary_of_changes = &drupal_static('data_request_summary_of_changes');

    if (isset($node->field_assignee[LANGUAGE_NONE][0]['uid']) && $previous_rm != $node->field_assignee[LANGUAGE_NONE][0]['uid']
     || isset($node->field_publisher_assignee[LANGUAGE_NONE][0]['uid']) && $previous_publisher_assignee != $node->field_publisher_assignee[LANGUAGE_NONE][0]['uid']) {

      // There is a new publisher assignee or new RM, this is special case where an assignee
      // must receive different message than all other subscribers.
      if (isset($node->field_publisher_assignee[LANGUAGE_NONE][0]['uid']) && $previous_publisher_assignee != $node->field_publisher_assignee[LANGUAGE_NONE][0]['uid']) {
        $assignee = user_load($node->field_publisher_assignee[LANGUAGE_NONE][0]['uid']);
      }
      else {
        $assignee = user_load($node->field_assignee[LANGUAGE_NONE][0]['uid']);
      }

      // Get data_request_assignee message bundle and set required fields.
      $message_assignee = message_create('data_request_assignee');
      $wrapper = entity_metadata_wrapper('message', $message_assignee);
      $wrapper->field_data_request_reference->set($node);
      $wrapper->field_data_request_assignee->set($assignee);

      $default_notifier = variable_get('message_subscribe_default_notifiers', array('email' => 'email'));
      $notifier = isset($assignee->field_digest_notifier[LANGUAGE_NONE][0]['value']) ? array($assignee->field_digest_notifier[LANGUAGE_NONE][0]['value'] => $assignee->field_digest_notifier[LANGUAGE_NONE][0]['value']) : $default_notifier;
      $subscribe_options = array(
        'uids' => array(
          $assignee->uid => array(
            'notifiers' => $notifier,
          ),
        ),
      );

      message_subscribe_send_message('node', $node, $message_assignee, $options, $subscribe_options);

      // Temporarily unsubscribe current assignee to avoid sending two messages
      // to this person (one about being current assignee, second about request update event)
      // if this person was subscribed before (e.g. was already an assignee before).
      flag('unflag', 'subscribe_node', $node->nid, $assignee);

      // Send data_request_update message to all subscribers.
      // First test if particular fields has changed and notify all non admin users.
      if(_dgu_data_set_request_fields_changed($fields_for_short_summary, $node, $previous_data_request_revision)) {

        // Get data_request_update message bundle and set required fields.
        $message_update = message_create('data_request_update');
        $wrapper = entity_metadata_wrapper('message', $message_update);
        $wrapper->field_data_request_reference->set($node);

        $summary_of_changes = _dgu_data_request_get_summary_of_changes($node, $previous_data_request_revision, $fields_for_short_summary);
        $uids = _dgu_data_set_request_get_subscribers($node->nid, $data_request_admin_roles, FALSE);
        if (!empty($uids)) {
          message_subscribe_send_message('node', $node, $message_update, $options, array('uids' => $uids));
        }

      }
      // Then notify admin users with full summary of changes.
      // Get data_request_update message bundle and set required fields.
      $message_update = message_create('data_request_update');
      $wrapper = entity_metadata_wrapper('message', $message_update);
      $wrapper->field_data_request_reference->set($node);

      $summary_of_changes = _dgu_data_request_get_summary_of_changes($node, $previous_data_request_revision);
      $uids = _dgu_data_set_request_get_subscribers($node->nid, $data_request_admin_roles);

      if (!empty($uids)) {
        message_subscribe_send_message('node', $node, $message_update, $options, array('uids' => $uids));
      }

      // Subscribe an assignee to following notifications about data request updates.
      flag('flag', 'subscribe_node', $node->nid, $assignee);
    }
    else {
      // Something else than assignee has been changed, simply notify all subscribers.

      // First notify admin users with full summary of changes.

      // Get data_request_update message bundle and set required fields.
      $message_update = message_create('data_request_update');
      $wrapper = entity_metadata_wrapper('message', $message_update);
      $wrapper->field_data_request_reference->set($node);

      $summary_of_changes = _dgu_data_request_get_summary_of_changes($node, $previous_data_request_revision);
      $admin_uids = _dgu_data_set_request_get_subscribers($node->nid, $data_request_admin_roles);
      if (!empty($admin_uids)) {
        message_subscribe_send_message('node', $node, $message_update, $options, array('uids' => $admin_uids));
      }

      // Then test if public fields has changed and notify all non admin users.
      if(_dgu_data_set_request_fields_changed($fields_for_short_summary, $node, $previous_data_request_revision)) {
        // Get data_request_update message bundle and set required fields.
        $message_update = message_create('data_request_update');
        $wrapper = entity_metadata_wrapper('message', $message_update);
        $wrapper->field_data_request_reference->set($node);

        $summary_of_changes = _dgu_data_request_get_summary_of_changes($node, $previous_data_request_revision, $fields_for_short_summary);
        $uids = _dgu_data_set_request_get_subscribers($node->nid, $data_request_admin_roles, FALSE);
        $non_admin_uids = array_diff($uids, $admin_uids);
        if (!empty($non_admin_uids)) {
          message_subscribe_send_message('node', $node, $message_update, $options, array('uids' => $non_admin_uids));
        }
      }
    }
  }
}


/**
 * Helper function to get all users subscribed to a data request.
 */
function _dgu_data_set_request_get_subscribers($nid, $rids, $in_rids = TRUE) {
  // Get all flags on given entity type.
  $flags = message_subscribe_flag_get_flags('node');
  $default_notifier = variable_get('message_subscribe_default_notifiers', array('email' => 'email'));
  $fids = array();
  foreach ($flags as $flag) {
    $fids[$flag->fid] = $flag->name;
  }
  // Query all the entity IDs inside the given flags. We don't use
  // flag_get_content_flags() as we want to get all the flaggings of an
  // entity-type in a single query.
  $query = db_select('flagging', 'f');
  $query->join('users', 'u', 'u.uid = f.uid');
  $query->leftJoin('users_roles', 'ur', 'ur.uid = u.uid');
  $query->leftJoin('field_data_field_digest_notifier', 'fdn', 'fdn.entity_id = u.uid');
  $query->fields('f', array('uid'));
  $query->fields('fdn', array('field_digest_notifier_value'))
    ->distinct()
    ->condition('f.entity_type', 'node')
    ->condition('f.entity_id', $nid)
    ->condition('fid', array_keys($fids), 'IN');
  if ($in_rids == TRUE) {
    $query->condition('ur.rid', $rids, 'IN');
  }
  else {
    $query->condition(db_or()->where('ur.rid NOT IN (' . implode (', ', $rids) . ')')->isNull('ur.rid'));
  }
  $result = $query->execute()->fetchAll();
  $uids = array();
  foreach ($result as $row) {
    $uids[$row->uid]['notifiers'] = isset($row->field_digest_notifier_value) ? array($row->field_digest_notifier_value => $row->field_digest_notifier_value) : $default_notifier;
  }
  return $uids;
}

/**
 * Helper function to test if particular fields has changed between revisions.
 */
function _dgu_data_set_request_fields_changed($fields_for_short_summary, $current_revision, $previous_revision) {
  foreach ($fields_for_short_summary as $field_name => $key) {
    $field_current_revision = isset($current_revision->{$field_name}[LANGUAGE_NONE][0][$key]) ? $current_revision->{$field_name}[LANGUAGE_NONE][0][$key] : NULL;
    $field_previous_revision = isset($previous_revision->{$field_name}[LANGUAGE_NONE][0][$key]) ? $previous_revision->{$field_name}[LANGUAGE_NONE][0][$key] : NULL;
    if ($field_current_revision !== $field_previous_revision) {
      return TRUE;
    }
  }
}

/**
 * Helper function to get summary of changes used in notification about data request update.
 */
function _dgu_data_request_get_summary_of_changes($current_revision, $previous_revision, $fields = array()) {

  //TODO use $fields to render particular summary

  $changes = array();
  $current_request = node_view($current_revision);
  $previous_request = node_view($previous_revision);

  foreach ((array)$current_request['#node'] as $key => $value) {
    // Iterate through all fields.
    if(strpos($key, 'field_') === 0) {
      if(!empty($fields)) {
        if(!in_array($key, array_keys($fields))) {
          continue;
        }
      }

      if ((isset($current_request[$key]['#items']) && !isset($previous_request[$key]['#items']))
       || (!isset($current_request[$key]['#items']) && isset($previous_request[$key]['#items']))
       || (isset($current_request[$key]['#items']) && isset($previous_request[$key]['#items']) && count($current_request[$key]['#items']) != count($previous_request[$key]['#items']))) {
        // If multi value field had different quantity of items it is modified.
        _dgu_data_set_request_render_changes($current_revision, $previous_revision, $key, $changes);
      }
      else {
        // Otherwise compare the values.
        $current_node = clone $current_request['#node'];
        $previous_node = clone $previous_request['#node'];

        if (isset($current_node->{$key}[LANGUAGE_NONE])) {
          foreach ($current_node->{$key}[LANGUAGE_NONE] as $index => &$item) {

            // Fix weird discrepancy on text_log fields, for some reason current revision has
            // only 'value' element, previous revision has also 'safe_value' and 'format'.
            $item['format'] = FALSE;
            $item['safe_value'] = FALSE;
            $previous_node->{$key}[LANGUAGE_NONE][$index]['format'] = FALSE;
            $previous_node->{$key}[LANGUAGE_NONE][$index]['safe_value'] = FALSE;

            if ($item != $previous_node->{$key}[LANGUAGE_NONE][$index]) {
              _dgu_data_set_request_render_changes($current_revision, $previous_revision, $key, $changes);
            }
          }
        }
      }
    }

  }

  if (!empty($changes)) {
    // Render summary.
    $output = "Summary of changes:\n";
    foreach ($changes as $field_name => $diff) {
      $output .= 'Field "' . $field_name . '" changed' . "\n";
      $output .= 'from: ' . $diff['previous'] . "\n";
      $output .= 'to:   ' . $diff['current'] . "\n";
      $output .= "\n";
    }
    return $output;
  }
}

/**
 * Helper function to render changes in a single field.
 */
function _dgu_data_set_request_render_changes($current_revision, $previous_revision, $key, &$changes) {
  $new_value = field_view_field('node', $current_revision, $key);
  $old_value = field_view_field('node', $previous_revision, $key);

  $new_value['#label_display'] = 'hidden';
  $old_value['#label_display'] = 'hidden';

  $title = $new_value['#title'] ? $new_value['#title'] : $old_value['#title'];

  $changes[$title] = array (
    'current' => substr(_dgu_data_set_request_remove_multiple_commas(strip_tags(str_replace('</', ', </', render($new_value)))), 0, -2),
    'previous' => substr(_dgu_data_set_request_remove_multiple_commas(strip_tags(str_replace('</', ', </', render($old_value)))), 0, -2),
  );
}

/**
 * Helper recursive function to get rid of multiple commas added before
 * each closing HTML tag in _dgu_data_set_request_render_changes() function.
 */
function _dgu_data_set_request_remove_multiple_commas($string) {
  $string = str_replace(', , ', ', ', $string);
  if (strpos($string, ', , ') !== FALSE) {
    $string = _dgu_data_set_request_remove_multiple_commas($string);
  }
  return $string;
}


/**
* Implements hook_token_info().
*/
function dgu_data_set_request_token_info() {
  $info['tokens']['message']['data_request-summary_of_changes'] = array(
    'name' => t('Data request - summary of changes'),
    'description' => t('Returns summary of changes in modified data request'),
  );
  return $info;
}
/**
* Implements hook_tokens().
*/
function dgu_data_set_request_tokens($type, $tokens, array $data = array(), array $options = array()) {
 $replacements = array();
   if ($type == 'message') {
     foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'data_request-summary_of_changes':
          $replacements[$original] = drupal_static('data_request_summary_of_changes');
          break;
      }
     }
  }
  return $replacements;
}

/**
 * Implements hook_preprocess_replies().
 */
function  dgu_data_set_request_preprocess_replies(&$variables) {
  if ($variables['bundle'] == 'review_comment' && $variables['entity_type'] == 'node') {
    if(!node_access('update', $variables['entity'])) {
      global $user;
      $assignees = dgu_data_set_request_publisher_assignee_get_assignees($variables['entity_id']);
      // Check if current user is or wes publisher assignee or if is an admin for referenced publisher or parent publisher.
      if(!in_array($user->uid, $assignees) && !(isset($variables['entity']->field_publisher_ref[LANGUAGE_NONE][0]['id']) && in_array($variables['entity']->field_publisher_ref[LANGUAGE_NONE][0]['id'], dgu_user_get_admin_publishers()))) {
        // Hide reply forms for users which haven't got access to edit entity.
        // We need to give them full access to create/update review_comment replies
        // but only on nodes they have permissions to edit, e.g data request assignee grant.
        unset($variables['replies']);
        unset($variables['reply_form']);
      }
    }
  }
}

/**
 * Implements hook_form_FORM_ID_form_alter().
 */
function dgu_data_set_request_form_reply_add_form_alter(&$form, &$form_state, $form_id) {
  if($form['#bundle'] == 'review_comment') {
    $form['field_review_comment'][LANGUAGE_NONE][0]['#title'] = 'Add review note <span class="submitted">(for non-public view)</span>';
    $form['submit']['#value'] = 'Submit review note';
  }
}

/**
 * Implements hook_preprocess_page().
 */
function dgu_data_set_request_preprocess_page(&$variables) {
  if (arg(0) == 'user' || arg(0) == 'admin') {
    if($count = _dgu_data_set_request_active_requests_publisher_admin_count()) {
      $link_title = 'view ' . format_plural($count, 'it', 'these') . ' now';
      drupal_set_message(
        'There ' . format_plural($count, 'is ', 'are ') . $count . ' active data ' . format_plural($count, 'request', 'requests')
        . ' for publishers that you administer, <a class="publishers-active-requests-link" href="/admin/workbench/content/data-requests?field_review_status_value%5B%5D=1&field_review_status_value%5B%5D=2&field_review_status_value%5B%5D=3&field_review_status_value%5B%5D=4&field_review_status_value%5B%5D=5&title=&field_publication_preference_value=All&field_barriers_reason_value=All&field_assignee_uid=All&field_publisher_ref_id=All&field_publisher_assignee_uid=All&items_per_page=25">'
        . $link_title . '</a>.<br />See <a href="/help?tour=data_requests_practitioners_guide">Data requests practitioners guide</a>.'
      );
    }
    if($count = _dgu_data_set_request_active_requests_publisher_assignee_count()) {
      $link_title = 'view ' . format_plural($count, 'it', 'these') . ' now';
      drupal_set_message(
        'You have ' . $count . ' active data ' . format_plural($count, 'request', 'requests')
        . ' that need' . format_plural($count, 's', '')
        . ' review, <a class="active-requests-link" href="/admin/workbench/content/active">'
        . $link_title . '</a>.<br />See <a href="/help?tour=data_requests_user_guide">Data requests user guide</a>.'
      );
    }
  }
}

function _dgu_data_set_request_active_requests_publisher_assignee_count() {
  global $user;
  if (in_array('data publisher', $user->roles)) {
    $query = db_select('field_data_field_publisher_assignee', 'a');
    $query->fields('a');
    $query->join('field_data_field_review_status', 's','a.entity_id = s.entity_id');
    $query->condition('a.field_publisher_assignee_uid', $user->uid)
      ->condition('s.field_review_status_value', 0, '<>')
      ->condition('s.field_review_status_value', 6, '<>');
    $result = $query->execute();
    return $result->rowCount();
  }
}

function _dgu_data_set_request_active_requests_publisher_admin_count() {
  global $user;
  if (in_array('data publisher', $user->roles) && !empty($user->data['ckan_publishers']) && in_array('admin', $user->data['ckan_publishers'])) {

    $publishers = array();
    foreach ($user->data['ckan_publishers'] as $publisher_id => $capacity) {

      if($capacity == 'admin' && !in_array($publisher_id, $publishers)) {
        $publishers = array_merge($publishers, dgu_user_get_publisher_with_children($publisher_id));
      }
    }

    $query = db_select('field_data_field_publisher_ref', 'p');
    $query->join('node', 'n', 'n.nid = p.entity_id');
    $query->fields('p');
    $query->join('field_data_field_review_status', 's','p.entity_id = s.entity_id');
    $query->condition('s.field_review_status_value', 0, '<>')
      ->condition('s.field_review_status_value', 6, '<>')
      ->condition('p.field_publisher_ref_id', $publishers, 'IN');
    $query->addTag('node_access');
    $result = $query->execute();
    return $result->rowCount();
  }
}


/**
 * Implements hook_bootstrap_tour_alter().
 */
function dgu_data_set_request_bootstrap_tour_alter($tour) {
  global $user;
  foreach($tour->steps as &$step) {
    if (substr($step['path'], 0, 13) == 'tour-redirect') {
      $redirect = substr($step['path'], 14);
      switch ($redirect) {
        case 'active-data-request':
          $query = db_select('field_data_field_publisher_assignee', 'a');
          $query->fields('a', array('entity_id'));
          $query->join('field_data_field_review_status', 's','a.entity_id = s.entity_id');
          $query->join('node', 'n','a.entity_id = n.nid');
          $query->condition('a.field_publisher_assignee_uid', $user->uid)
            ->condition('s.field_review_status_value', 0, '<>')
            ->condition('s.field_review_status_value', 6, '<>')
            ->orderBy('n.nid', 'DESC');
          $active_request_nid = $query->execute()->fetchField();
          $query_parameters = drupal_get_query_parameters();
          $query = drupal_http_build_query($query_parameters);
          $step['path'] = drupal_get_path_alias('node/' . $active_request_nid) . '?' . $query;
          break;
        case 'publisher-active-data-request-url':
          $query_parameters = drupal_get_query_parameters();
          $query_parameters['field_review_status_value'] = array('1','2','3','4','5');
          $query_parameters['field_publication_preference_value'] = 'All';
          $query_parameters['field_barriers_reason_value'] = 'All';
          $query_parameters['field_assignee_uid'] = 'All';
          $query_parameters['field_publisher_ref_id'] = 'All';
          $query_parameters['field_publisher_assignee_uid'] = 'All';
          $query_parameters['items_per_page'] = '25';
          $query = drupal_http_build_query($query_parameters);
          $step['path'] = 'admin/workbench/content/data-requests' . '?' . $query;
          break;
        case 'publisher-active-data-request':
          $publishers = array();
          foreach ($user->data['ckan_publishers'] as $publisher_id => $capacity) {
            if($capacity == 'admin' && !in_array($publisher_id, $publishers)) {
              $publishers = array_merge($publishers, dgu_user_get_publisher_with_children($publisher_id));
            }
          }
          $query = db_select('field_data_field_publisher_ref', 'p');
          $query->join('node', 'n', 'n.nid = p.entity_id');
          $query->fields('p', array('entity_id'));
          $query->join('field_data_field_review_status', 's','p.entity_id = s.entity_id');
          $query->join('node', 'n','p.entity_id = n.nid');
          $query->condition('s.field_review_status_value', 0, '<>')
            ->condition('s.field_review_status_value', 6, '<>')
            ->condition('p.field_publisher_ref_id', $publishers, 'IN')
            ->orderBy('n.nid', 'DESC');
          $query->addTag('node_access');
          $active_request_nid = $query->execute()->fetchField();
          $query_parameters = drupal_get_query_parameters();
          $query = drupal_http_build_query($query_parameters);
          $step['path'] = drupal_get_path_alias('node/' . $active_request_nid) . '?' . $query;
          break;
        case 'active-data-request-author':
          $query = db_select('field_data_field_publisher_assignee', 'a');
          $query->fields('a', array('entity_id'));
          $query->join('field_data_field_review_status', 's','a.entity_id = s.entity_id');
          $query->condition('a.field_publisher_assignee_uid', $user->uid)
            ->condition('s.field_review_status_value', 0, '<>')
            ->condition('s.field_review_status_value', 6, '<>')
            ->orderBy('entity_id', 'DESC');
          $active_request_nid = $query->execute()->fetchField();
          $active_request = node_load($active_request_nid);
          $query_parameters = drupal_get_query_parameters();
          $query = drupal_http_build_query($query_parameters);
          $step['path'] = drupal_get_path_alias('user/' . $active_request->uid) . '?' . $query;
          break;

        case 'active-data-request-author-contact':
          $query = db_select('field_data_field_publisher_assignee', 'a');
          $query->fields('a', array('entity_id'));
          $query->join('field_data_field_review_status', 's','a.entity_id = s.entity_id');
          $query->condition('a.field_publisher_assignee_uid', $user->uid)
            ->condition('s.field_review_status_value', 0, '<>')
            ->condition('s.field_review_status_value', 6, '<>')
            ->orderBy('entity_id', 'DESC');
          $active_request_nid = $query->execute()->fetchField();
          $active_request = node_load($active_request_nid);
          $query_parameters = drupal_get_query_parameters();
          $query = drupal_http_build_query($query_parameters);
          $step['path'] = 'user/' . $active_request->uid . '/contact?' . $query;
          break;
      }
    }
  }
}


/**
 * Implements hook_views_pre_view().
 */
function dgu_data_set_request_views_pre_view(&$view, &$display_id, &$args) {
  global $user;
  // If not moderator or editor then unset 'Data request' view header which tells about 'Needs review' page.
  if ($view->name == 'data_requests_administration' && $display_id == 'page_1') {
    if (!in_array('moderator', $user->roles) && !in_array('editor', $user->roles)) {
      $view->set_item_option($display_id, 'header', 'area', 'content', '');
    }
  }
}

/**
 * Implements hook_views_query_alter().
 */
function dgu_data_set_request_views_query_alter(&$view, &$query) {
  global $user;
  if ($view->name == 'data_requests_administration' && $view->current_display == 'page_1' && !in_array('data request administrator', $user->roles) && !in_array('editor', $user->roles)) {
    $publishers = array();
    if (!empty($user->data['ckan_publishers']) && in_array('admin', $user->data['ckan_publishers'])) {
      // Limit requests only to publisher (with all sub publishers) in which current user has 'admin' capacity.
      $publishers = dgu_user_get_admin_publishers();
    }
    elseif (in_array('data publisher', $user->roles)) {
      // Limit requests only to publishers (without sub publishers) in which current user has 'editor' capacity.
      $full_account = user_load($user->uid);

      foreach ($full_account->field_publishers[LANGUAGE_NONE] as $publisher_ref) {
        $publishers[] = $publisher_ref['target_id'];
      }
    }
    else {
      return;
    }

    $query->where[1]['conditions'][] = array(
      'field' => 'field_data_field_publisher_ref.field_publisher_ref_id',
      'value' => array($publishers),
      'operator' => 'in'
    );
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function dgu_data_set_request_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
  if ($form_state['view']->name == 'data_requests_administration' && $form_state['view']->current_display == 'page_1') {

    if ($admin_publishers = dgu_user_get_admin_publishers()) {
      // Remove publishers which are filtered out in dgu_user_views_query_alter() from exposed filter.
      foreach ($form['field_publisher_ref_id']['#options'] as $key => $value) {
        if (!in_array($key, $admin_publishers) && $key != 'All') {
          unset($form['field_publisher_ref_id']['#options'][$key]);
        }
      }

      $query = db_select('field_data_field_publisher_assignee', 'pa');
      $query->join('field_data_field_publisher_ref', 'p', 'p.entity_id = pa.entity_id');
      $query->fields('pa', array('field_publisher_assignee_uid'))
        ->condition('p.field_publisher_ref_id', $admin_publishers, 'IN')
        ->distinct();
      $publisher_assignees = $query->execute()->fetchCol();

      // Also remove not relevant publisher assignees.
      foreach ($form['field_publisher_assignee_uid']['#options'] as $key => $value) {
        if (!in_array($key, $publisher_assignees) && $key != 'All') {
          unset($form['field_publisher_assignee_uid']['#options'][$key]);
        }
      }
    }
  }
}

